apiVersion: kustomize.config.k8s.io/v1beta1 # 커스터마이즈의 API 스키마 버전
kind: Kustomization # 메니페스트를 통해 정의할 리소스의 유형

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: catalog-config
    files:
      - application.yml
    options:
      labels:
        app: catalog-service